name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install pytest
        run: pip install pytest

      - name: Debug - Répertoire de travail
        run: |
          echo "Répertoire courant : $(pwd)"
          ls -la

      - name: Debug - Lister les fichiers de test
        run: find . -name "test_*.py"

      - name: Debug - Permissions des fichiers
        run: ls -la tests/

      - name: Debug - Versions de Python et pytest
        run: |
          python --version
          pip show pytest

      - name: Run tests
        run: pytest tests/

  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Run Trivy vulnerability scanner in filesystem mode and output in SARIF format
      - name: Run Trivy vulnerability scanner in filesystem mode
        uses: aquasecurity/trivy-action@b3dafe507ffa004210975439a1e6156b8ebb3f50
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      # Upload Trivy scan results to GitHub Security tab
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
          
